package config

const (

	//---------------- wallet 模块 --------------------------
	MSGID_multicast_vote_recv      = 10200 //接收见证人投票广播
	MSGID_multicast_blockhead      = 10201 //接收区块头广播
	MSGID_heightBlock              = 10202 //查询邻居节点区块高度
	MSGID_heightBlock_recv         = 10203 //查询邻居节点区块高度_返回
	MSGID_getStartBlockHead        = 10204 //查询邻居节点的起始区块头
	MSGID_getStartBlockHead_recv   = 10205 //查询邻居节点的起始区块头_返回
	MSGID_getBlockHeadVO           = 10206 //查询整个区块，包含头和交易
	MSGID_getBlockHeadVO_recv      = 10207 //查询整个区块，包含头和交易_返回
	MSGID_multicast_transaction    = 10208 //接收交易广播
	MSGID_getUnconfirmedBlock      = 10209 //从邻居节点获取未确认的区块
	MSGID_getUnconfirmedBlock_recv = 10210 //从邻居节点获取未确认的区块_返回

	MSGID_multicast_return        = 10211 //收到广播消息回复
	MSGID_getblockforwitness      = 10212 //从邻居节点获取指定见证人的区块
	MSGID_getblockforwitness_recv = 10213 //从邻居节点获取指定见证人的区块_返回

	MSGID_getDBKey_one      = 10214 //查询远程数据库的key对应的value保存到本地数据库
	MSGID_getDBKey_one_recv = 10215 //查询远程数据库的key对应的value保存到本地数据库_返回

	MSGID_multicast_find_witness      = 10216 //广播寻找见证人
	MSGID_multicast_find_witness_recv = 10217 //回复见证人网络地址

	MSGID_getBlockLastCurrent      = 10218 //从邻居节点获取已经确认的最高区块
	MSGID_getBlockLastCurrent_recv = 10219 //从邻居节点获取已经确认的最高区块_返回

	MSGID_multicast_witness_blockhead          = 10220 //接收见证人之间的区块hash
	MSGID_multicast_witness_blockhead_recv     = 10221 //接收见证人之间的区块hash_返回
	MSGID_multicast_witness_blockhead_get      = 10222 //通过接收到的区块hash获取区块
	MSGID_multicast_witness_blockhead_get_recv = 10223 //通过接收到的区块hash获取区块_返回

	MSGID_uniformity_multicast_witness_blockhead         = 10224 //接收见证人之间的区块hash
	MSGID_uniformity_multicast_witness_blockhead_recv    = 10225 //接收见证人之间的区块hash_返回
	MSGID_uniformity_multicast_witness_block_get         = 10226 //通过接收到的区块hash获取区块
	MSGID_uniformity_multicast_witness_block_get_recv    = 10227 //通过接收到的区块hash获取区块_返回
	MSGID_uniformity_multicast_witness_block_import      = 10228 //接收导入区块命令
	MSGID_uniformity_multicast_witness_block_import_recv = 10229 //接收导入区块命令_返回

	MSGID_multicast_blockhead_sign      = 10230 //接收区块头签名广播
	MSGID_multicast_blockhead_sign_recv = 10231 //接收区块头签名广播_返回

	MSGID_p2p_block_ack      = 10232 //接收区块确认广播
	MSGID_p2p_block_ack_recv = 10233 //接收区块确认广播_返回

	MSGID_p2p_node_get_addrnonce     = 20003 //查询特定节点，地址下一个使用nonce
	MSGID_p2p_node_get_addrnonce_rev = 20004 //回复查询特定节点，地址下一个使用nonce

	MSGID_p2p_node_get_addrbalance     = 20005 //查询特定节点，地址余额
	MSGID_p2p_node_get_addrbalance_rev = 20006 //回复查询特定节点，地址余额

	MSGID_LIGHT_NODE_GET_ACCOUNT_INFO     = 20100 //查询账号信息
	MSGID_LIGHT_NODE_GET_ACCOUNT_INFO_REV = 20101 //查询账号信息

	MSGID_LIGHT_NODE_GET_ACCOUNT_MSG     = 20102 //获取账号详情
	MSGID_LIGHT_NODE_GET_ACCOUNT_MSG_REV = 20103 //获取账号详情返回

	MSGID_LIGHT_NODE_GET_HISTORY_TX_RECORD     = 20104 //获取账号详情
	MSGID_LIGHT_NODE_GET_HISTORY_TX_RECORD_REV = 20105 //获取账号详情返回

	MSGID_LIGHT_NODE_CHECK_TX_ONLINE     = 20106 //获取账号详情
	MSGID_LIGHT_NODE_CHECK_TX_ONLINE_REV = 20107 //获取账号详情返回

	MSGID_LIGHT_NODE_GET_BLOCK_INFO     = 20108 //获取账号详情
	MSGID_LIGHT_NODE_GET_BLOCK_INFO_REV = 20109 //获取账号详情返回

	MSGID_LIGHT_NODE_GET_BLOCK_INFO_BY_HASH     = 20110 //获取账号详情
	MSGID_LIGHT_NODE_GET_BLOCK_INFO_BY_HASH_REV = 20111 //获取账号详情返回

	MSGID_LIGHT_NODE_GET_BLOCK_RANGE_INFO     = 20112 //通过一定范围的区块高度查询多个区块详细信息
	MSGID_LIGHT_NODE_GET_BLOCK_RANGE_INFO_REV = 20113 //通过一定范围的区块高度查询多个区块详细信息返回

	MSGID_LIGHT_NODE_GET_BLOCK_RANGE_INFO_PROTO     = 20114 //通过一定范围的区块高度查询多个区块详细信息proto
	MSGID_LIGHT_NODE_GET_BLOCK_RANGE_INFO_PROTO_REV = 20115 //通过一定范围的区块高度查询多个区块详细信息返回proto

	MSGID_LIGHT_NODE_GET_BLOCK_DEAL_TX_TIME     = 20116 //查询区块处理交易时间
	MSGID_LIGHT_NODE_GET_BLOCK_DEAL_TX_TIME_REV = 20117 //查询区块处理交易时间

	MSGID_LIGHT_NODE_GET_DEPOSIT_NUM     = 20118 //获取节点质押数量
	MSGID_LIGHT_NODE_GET_DEPOSIT_NUM_REV = 20119 //获取节点质押数量

	MSGID_LIGHT_NODE_GET_LIGHT_LIST     = 20120 //获取所有轻节点列表
	MSGID_LIGHT_NODE_GET_LIGHT_LIST_REV = 20121 //获取所有轻节点列表

	MSGID_LIGHT_NODE_GET_NODE_NUM     = 20122 //获取节点数量
	MSGID_LIGHT_NODE_GET_NODE_NUM_REV = 20123 //获取节点数量

	MSGID_LIGHT_NODE_DEPOSITIN     = 20124 //缴纳押金，成为见证人
	MSGID_LIGHT_NODE_DEPOSITIN_REV = 20125 //缴纳押金，成为见证人

	MSGID_LIGHT_NODE_DEPOSIT_OUT     = 20126 //退还押金
	MSGID_LIGHT_NODE_DEPOSIT_OUT_REV = 20127 //退还押金

	MSGID_LIGHT_NODE_VOTEINNEW     = 20128 //给见证人投票押金
	MSGID_LIGHT_NODE_VOTEINNEW_REV = 20129 //给见证人投票押金

	MSGID_LIGHT_NODE_CHECKCANWITNESS     = 20130 //检查是否能成为见证者节点
	MSGID_LIGHT_NODE_CHECKCANWITNESS_REV = 20131 //检查是否能成为见证者节点

	MSGID_LIGHT_NODE_VOTEOUTNEW     = 20132 //退还给见证人投票押金
	MSGID_LIGHT_NODE_VOTEOUTNEW_REV = 20133 //退还给见证人投票押金

	MSGID_LIGHT_NODE_GETWITNESSINFO     = 20134 //查询见证人状态
	MSGID_LIGHT_NODE_GETWITNESSINFO_REV = 20135 //查询见证人状态

	MSGID_LIGHT_NODE_GETCANDIDATELIST     = 20136 //获得候选见证人列表
	MSGID_LIGHT_NODE_GETCANDIDATELIST_REV = 20137 //获得候选见证人列表

	MSGID_LIGHT_NODE_GETWITNESSESLIST     = 20138 //获得见证人列表
	MSGID_LIGHT_NODE_GETWITNESSESLIST_REV = 20139 //获得见证人列表

	MSGID_LIGHT_NODE_GETCOMMUNITYLISTNEW     = 20140 //获取社区节点列表
	MSGID_LIGHT_NODE_GETCOMMUNITYLISTNEW_REV = 20141 //获取社区节点列表

	MSGID_LIGHT_NODE_GETVOTELISTNEW     = 20142 //获得自己投过票的列表
	MSGID_LIGHT_NODE_GETVOTELISTNEW_REV = 20143 //获得自己投过票的列表

	MSGID_LIGHT_NODE_GETCOMMUNITYREWARD     = 20144 //获取一个社区累计奖励
	MSGID_LIGHT_NODE_GETCOMMUNITYREWARD_REV = 20145 //获取一个社区累计奖励

	MSGID_LIGHT_NODE_SENDCOMMUNITYREWARD     = 20146 //分发社区奖励
	MSGID_LIGHT_NODE_SENDCOMMUNITYREWARD_REV = 20147 //分发社区奖励

	MSGID_LIGHT_NODE_GETVOTEADDR     = 20148 //查询一个地址给谁投票，票数
	MSGID_LIGHT_NODE_GETVOTEADDR_REV = 20149 //查询一个地址给谁投票，票数

	MSGID_LIGHT_NODE_FIND_NAME     = 20150 //查询域名
	MSGID_LIGHT_NODE_FIND_NAME_REV = 20151 //查询域名

	MSGID_LIGHT_NODE_FIND_ROLE_OF_ADDRESS     = 20152 //查询一个地址角色
	MSGID_LIGHT_NODE_FIND_ROLE_OF_ADDRESS_REV = 20153 //查询一个地址角色

	MSGID_LIGHT_NODE_FIND_BALANCE_OF_ADDRESS     = 20154 //查询一个地址余额
	MSGID_LIGHT_NODE_FIND_BALANCE_OF_ADDRESS_REV = 20155 //查询一个地址余额

	MSGID_LIGHT_NODE_GETADDRESSTX     = 20156 //获取地址交易
	MSGID_LIGHT_NODE_GETADDRESSTX_REV = 20157 //获取地址交易

	MSGID_LIGHT_NODE_GETALLTX     = 20158 //获取所有交易
	MSGID_LIGHT_NODE_GETALLTX_REV = 20159 //获取所有交易

	MSGID_LIGHT_NODE_GETMINERBLOCK     = 20160 //获取挖矿交易
	MSGID_LIGHT_NODE_GETMINERBLOCK_REV = 20161 //获取挖矿交易

	MSGID_LIGHT_NODE_GETLIGHTNODEDETAIL     = 20162 //获取轻节点详情
	MSGID_LIGHT_NODE_GETLIGHTNODEDETAIL_REV = 20163 //获取轻节点详情

	MSGID_LIGHT_NODE_GETWITNESSNODEDETAIL     = 20164 //获取见证者节点详情
	MSGID_LIGHT_NODE_GETWITNESSNODEDETAIL_REV = 20165 //获取见证者节点详情

	MSGID_LIGHT_NODE_GETCOMMUNITYNODEDETAIL     = 20166 //获取社区节点详情
	MSGID_LIGHT_NODE_GETCOMMUNITYNODEDETAIL_REV = 20167 //获取社区节点详情

	MSGID_LIGHT_NODE_GETCOMMUNITYLISTFORMINER     = 20168 //获取社区节点列表
	MSGID_LIGHT_NODE_GETCOMMUNITYLISTFORMINER_REV = 20169 //获取社区节点列表

	MSGID_LIGHT_NODE_GETWITNESSESLISTWITHPAGE     = 20170 //获得候选见证人和见证人列表 带翻页
	MSGID_LIGHT_NODE_GETWITNESSESLISTWITHPAGE_REV = 20171 //获得候选见证人和见证人列表 带翻页

	MSGID_LIGHT_NODE_GETWITNESSESINFOFORMINER     = 20172 //获得某个候选见证人和见证人信息
	MSGID_LIGHT_NODE_GETWITNESSESINFOFORMINER_REV = 20173 //获得某个候选见证人和见证人信息

	MSGID_LIGHT_NODE_GETWITNESSESLISTV0WITHPAGE     = 20174 //获得见证人列表 带翻页
	MSGID_LIGHT_NODE_GETWITNESSESLISTV0WITHPAGE_REV = 20175 //获得见证人列表 带翻页

	MSGID_LIGHT_NODE_GETWITNESSESBACKUPLISTV0WITHPAGE     = 20176 //获得候选见证人列表 带翻页
	MSGID_LIGHT_NODE_GETWITNESSESBACKUPLISTV0WITHPAGE_REV = 20177 //获得候选见证人列表 带翻页

	MSGID_LIGHT_NODE_GETDEPOSITNUMFORALL     = 20178 //获取总的节点质押量
	MSGID_LIGHT_NODE_GETDEPOSITNUMFORALL_REV = 20179 //获取总的节点质押量

	MSGID_LIGHT_NODE_GETABIINPUT     = 20180 //获取批量交易input
	MSGID_LIGHT_NODE_GETABIINPUT_REV = 20181 //获取批量交易input

	MSGID_LIGHT_NODE_GETTXGAS     = 20182 //根据交易类型获取交易gas 默认普通交易
	MSGID_LIGHT_NODE_GETTXGAS_REV = 20183 //根据交易类型获取交易gas 默认普通交易

	MSGID_LIGHT_NODE_GETCONTRACTEVENT     = 20184 //根据区块高度和交易hash获取奖励合约事件
	MSGID_LIGHT_NODE_GETCONTRACTEVENT_REV = 20185 //根据区块高度和交易hash获取奖励合约事件

	MSGID_LIGHT_NODE_ADDERC20     = 20186 //收藏代币
	MSGID_LIGHT_NODE_ADDERC20_REV = 20187 //收藏代币

	MSGID_LIGHT_NODE_DELERC20     = 20188 //移除代币
	MSGID_LIGHT_NODE_DELERC20_REV = 20189 //移除代币

	MSGID_LIGHT_NODE_GETERC20     = 20190 //获取指定key代币
	MSGID_LIGHT_NODE_GETERC20_REV = 20191 //获取指定key代币

	MSGID_LIGHT_NODE_GETERC20VALUE     = 20192 //获取收藏的代币(余额）
	MSGID_LIGHT_NODE_GETERC20VALUE_REV = 20193 //获取收藏的代币(余额）

	MSGID_LIGHT_NODE_SEARCHERC20     = 20194 //搜索代币
	MSGID_LIGHT_NODE_SEARCHERC20_REV = 20195 //搜索代币

	MSGID_LIGHT_NODE_GETERC20SUMBALANCE     = 20196 //获取多代币地址的总余额
	MSGID_LIGHT_NODE_GETERC20SUMBALANCE_REV = 20197 //获取多代币地址的总余额

	MSGID_LIGHT_NODE_TRANSFERERC20     = 20198 //代币转账
	MSGID_LIGHT_NODE_TRANSFERERC20_REV = 20199 //代币转账

	MSGID_LIGHT_NODE_GETTOKENBALANCE     = 20200 //获取代币余额
	MSGID_LIGHT_NODE_GETTOKENBALANCE_REV = 20201 //获取代币余额

	MSGID_LIGHT_NODE_GETTOKENBALANCES     = 20202 //获取多地址代币余额
	MSGID_LIGHT_NODE_GETTOKENBALANCES_REV = 20203 //获取多地址代币余额

	MSGID_LIGHT_NODE_GETREWARDCONTRACT     = 20204 //获取合约奖励
	MSGID_LIGHT_NODE_GETREWARDCONTRACT_REV = 20205 //获取合约奖励

	//-------contract部分-----
	MSGID_LIGHT_NODE_CREATECONTRACTBYTX     = 20206 //创建合约
	MSGID_LIGHT_NODE_CREATECONTRACTBYTX_REV = 20207 //创建合约

	MSGID_LIGHT_NODE_CALLCONTRACTBYTX     = 20208 //调用合约
	MSGID_LIGHT_NODE_CALLCONTRACTBYTX_REV = 20209 //调用合约

	MSGID_LIGHT_NODE_CALLCONTRACTSTACK     = 20210 //本地模拟调用
	MSGID_LIGHT_NODE_CALLCONTRACTSTACK_REV = 20211 //本地模拟调用

	MSGID_LIGHT_NODE_GETCONTRACTCOUNT     = 20212 //查询有效合约的数量
	MSGID_LIGHT_NODE_GETCONTRACTCOUNT_REV = 20213 //查询有效合约的数量

	MSGID_LIGHT_NODE_GETCONTRACTSOURCE     = 20214 //获取合约源代码
	MSGID_LIGHT_NODE_GETCONTRACTSOURCE_REV = 20215 //获取合约源代码

	MSGID_LIGHT_NODE_GETCONTRACTINFO     = 20216 //获取合约状态
	MSGID_LIGHT_NODE_GETCONTRACTINFO_REV = 20217 //获取合约状态

	MSGID_LIGHT_NODE_GETSPECIALCONTRACT     = 20218 //获取特定类型合约地址
	MSGID_LIGHT_NODE_GETSPECIALCONTRACT_REV = 20219 //获取特定类型合约地址

	MSGID_LIGHT_NODE_CHECKCONTRACT     = 20220 //验证合约
	MSGID_LIGHT_NODE_CHECKCONTRACT_REV = 20221 //验证合约

	MSGID_LIGHT_NODE_WITHDRAWREWARD     = 20222 //提现奖励
	MSGID_LIGHT_NODE_WITHDRAWREWARD_REV = 20223 //提现奖励

	MSGID_LIGHT_NODE_GETREWARDHISTORY     = 20224 //获取奖励历史
	MSGID_LIGHT_NODE_GETREWARDHISTORY_REV = 20225 //获取奖励历史

	MSGID_LIGHT_NODE_RECEIVETCOIN     = 20226 //领取测试币
	MSGID_LIGHT_NODE_RECEIVETCOIN_REV = 20227 //领取测试币

	//-------ens部分-----
	MSGID_LIGHT_NODE_DELAYBASEREGISTAR     = 20228 //部署注册器
	MSGID_LIGHT_NODE_DELAYBASEREGISTAR_REV = 20229 //部署注册器

	MSGID_LIGHT_NODE_ADDDOMAIN     = 20230 //请求注册器合约添加域名
	MSGID_LIGHT_NODE_ADDDOMAIN_REV = 20231 //请求注册器合约添加域名

	MSGID_LIGHT_NODE_ABORTADDDOMAIN     = 20232 //终止添加域名
	MSGID_LIGHT_NODE_ABORTADDDOMAIN_REV = 20233 //终止添加域名

	MSGID_LIGHT_NODE_MODIFYADDDOMAIN     = 20234 //修改添加域名
	MSGID_LIGHT_NODE_MODIFYADDDOMAIN_REV = 20235 //修改添加域名

	MSGID_LIGHT_NODE_SETDOMAINMANGER     = 20236 //设置控制器合约为根域名管理员
	MSGID_LIGHT_NODE_SETDOMAINMANGER_REV = 20237 //设置控制器合约为根域名管理员

	MSGID_LIGHT_NODE_SETDOMAINIMRESOLVER     = 20238 //解析主链地址
	MSGID_LIGHT_NODE_SETDOMAINIMRESOLVER_REV = 20239 //解析主链地址

	MSGID_LIGHT_NODE_SETDOMAINOTHERRESOLVER     = 20240 //设置其他币种解析
	MSGID_LIGHT_NODE_SETDOMAINOTHERRESOLVER_REV = 20241 //设置其他币种解析

	MSGID_LIGHT_NODE_DOMAINTRANSFER     = 20242 //转让
	MSGID_LIGHT_NODE_DOMAINTRANSFER_REV = 20243 //转让

	MSGID_LIGHT_NODE_DOMAINWITHDRAW     = 20244 //提现
	MSGID_LIGHT_NODE_DOMAINWITHDRAW_REV = 20245 //提现

	MSGID_LIGHT_NODE_REGISTERDOMAIN     = 20246 //注册域名
	MSGID_LIGHT_NODE_REGISTERDOMAIN_REV = 20247 //注册域名

	MSGID_LIGHT_NODE_RENEWDOMAIN     = 20248 //续费域名
	MSGID_LIGHT_NODE_RENEWDOMAIN_REV = 20249 //续费域名

	MSGID_LIGHT_NODE_GETLAUNCHDOMAINS     = 20250 //获取投放的域名列表
	MSGID_LIGHT_NODE_GETLAUNCHDOMAINS_REV = 20251 //获取投放的域名列表

	MSGID_LIGHT_NODE_GETHOLDERNUM     = 20252 //获取持有人数量
	MSGID_LIGHT_NODE_GETHOLDERNUM_REV = 20253 //获取持有人数量

	MSGID_LIGHT_NODE_GETDOMAINEXP     = 20254 //获取域名过期时间
	MSGID_LIGHT_NODE_GETDOMAINEXP_REV = 20255 //获取域名过期时间

	MSGID_LIGHT_NODE_GETDOMAINOWNER     = 20256 //获取域名持有人
	MSGID_LIGHT_NODE_GETDOMAINOWNER_REV = 20257 //获取域名持有人

	MSGID_LIGHT_NODE_GETDOMAINDETAIL     = 20258 //获取域名详情
	MSGID_LIGHT_NODE_GETDOMAINDETAIL_REV = 20259 //获取域名详情

	MSGID_LIGHT_NODE_GETDOMAINRESOLVER     = 20260 //获取域名的解析
	MSGID_LIGHT_NODE_GETDOMAINRESOLVER_REV = 20261 //获取域名的解析

	MSGID_LIGHT_NODE_GETDOMAINOTHERRESOLVER     = 20262 //获取其他币种解析
	MSGID_LIGHT_NODE_GETDOMAINOTHERRESOLVER_REV = 20263 //获取其他币种解析

	MSGID_LIGHT_NODE_GETMYROOTDOMAIN     = 20264 //获取我名下的根域名
	MSGID_LIGHT_NODE_GETMYROOTDOMAIN_REV = 20265 //获取我名下的根域名

	MSGID_LIGHT_NODE_GETMYSUBDOMAIN     = 20266 //获取我名下的子域名
	MSGID_LIGHT_NODE_GETMYSUBDOMAIN_REV = 20267 //获取我名下的子域名

	MSGID_LIGHT_NODE_GETENSCONTRACT     = 20268 //获取平台域名的基础合约地址
	MSGID_LIGHT_NODE_GETENSCONTRACT_REV = 20269 //获取平台域名的基础合约地址

	MSGID_LIGHT_NODE_GETROOTINCOME     = 20270 //获取域名收入
	MSGID_LIGHT_NODE_GETROOTINCOME_REV = 20271 //获取域名收入

	MSGID_LIGHT_NODE_FINDBLOCKRANGEV1     = 20272 //获取一定区块高度范围内的区块新版本
	MSGID_LIGHT_NODE_FINDBLOCKRANGEV1_REV = 20273 //获取一定区块高度范围内的区块新版本

	MSGID_LIGHT_NODE_LAUNCHDOMAIN     = 20274 //投放域名
	MSGID_LIGHT_NODE_LAUNCHDOMAIN_REV = 20275 //投放域名

	MSGID_LIGHT_NODE_ABORTLAUNCHDOMAIN     = 20276 //终止投放域名
	MSGID_LIGHT_NODE_ABORTLAUNCHDOMAIN_REV = 20277 //终止投放域名

	MSGID_LIGHT_NODE_MODIFYLAUNCHDOMAIN     = 20278 //修改投放域名
	MSGID_LIGHT_NODE_MODIFYLAUNCHDOMAIN_REV = 20279 //修改投放域名

	MSGID_LIGHT_NODE_SETLOCKDOMAIN     = 20280 //锁定域名
	MSGID_LIGHT_NODE_SETLOCKDOMAIN_REV = 20281 //锁定域名

	MSGID_LIGHT_NODE_UNLOCKDOMAIN     = 20282 //解锁域名
	MSGID_LIGHT_NODE_UNLOCKDOMAIN_REV = 20283 //解锁域名

	MSGID_LIGHT_NODE_GETLOCKDOMAINS     = 20284 //获取锁定域名列表
	MSGID_LIGHT_NODE_GETLOCKDOMAINS_REV = 20285 //获取锁定域名列表

	MSGID_LIGHT_NODE_GETDOMAINCOST     = 20286 //获取域名费用
	MSGID_LIGHT_NODE_GETDOMAINCOST_REV = 20287 //获取域名费用

	MSGID_LIGHT_NODE_GETSINGLEDOMAINCOST     = 20288 //获取单个域名费用
	MSGID_LIGHT_NODE_GETSINGLEDOMAINCOST_REV = 20289 //获取单个域名费用

	MSGID_LIGHT_NODE_GETHOTROOTDOMAIN     = 20290 //获取热度高的根域名
	MSGID_LIGHT_NODE_GETHOTROOTDOMAIN_REV = 20291 //获取热度高的根域名

	MSGID_LIGHT_NODE_SETREVERSERESOLVERNAME     = 20292 //反向解析设置名称
	MSGID_LIGHT_NODE_SETREVERSERESOLVERNAME_REV = 20293 //反向解析设置名称

	MSGID_LIGHT_NODE_DELDOMAINIMRESOLVER     = 20294 //删除解析
	MSGID_LIGHT_NODE_DELDOMAINIMRESOLVER_REV = 20295 //删除解析

	//--------base补充模块---------
	MSGID_LIGHT_NODE_HANDLEGETNEWADDRESS     = 20296 //创建新地址
	MSGID_LIGHT_NODE_HANDLEGETNEWADDRESS_REV = 20297 //创建新地址

	MSGID_LIGHT_NODE_HANDLELISTALLADDRESS     = 20298 //列出节点私钥存储的所有地址及余额
	MSGID_LIGHT_NODE_HANDLELISTALLADDRESS_REV = 20299 //列出节点私钥存储的所有地址及余额

	MSGID_LIGHT_NODE_GETBALANCEOFADDR     = 20300 //获取地址余额
	MSGID_LIGHT_NODE_GETBALANCEOFADDR_REV = 20301 //获取地址余额

	MSGID_LIGHT_NODE_SENDTOADDRESS     = 20302 //转账
	MSGID_LIGHT_NODE_SENDTOADDRESS_REV = 20303 //转账

	MSGID_LIGHT_NODE_SENDTOADDRESSMORE     = 20304 //批量转账
	MSGID_LIGHT_NODE_SENDTOADDRESSMORE_REV = 20305 //批量转账

	MSGID_LIGHT_NODE_GETNONCE     = 20306 //获取某个地址的nonce
	MSGID_LIGHT_NODE_GETNONCE_REV = 20307 //获取某个地址的nonce

	MSGID_getBlockHeadVOMore      = 10234 //一次查询多个区块，包含头和交易
	MSGID_getBlockHeadVOMore_recv = 10235 //一次查询多个区块，包含头和交易_返回

	MSGID_LIGHT_NODE_CREATEOFFLINETXV1     = 20308 //构建普通离线交易
	MSGID_LIGHT_NODE_CREATEOFFLINETXV1_REV = 20309 //构建普通离线交易

	MSGID_p2p_node_get_addr_lock_balance     = 20310 //查询特定节点，地址余额
	MSGID_p2p_node_get_addr_lock_balance_rev = 20311 //回复查询特定节点，地址余额

	MSGID_P2P_NODE_HANDLEMULTIACCOUNTS     = 20312 //查询特定节点，地址余额
	MSGID_P2P_NODE_HANDLEMULTIACCOUNTS_rev = 20313 //回复查询特定节点，地址余额

	MSGID_GET_FULL_NODE     = 20314 //获取全节点
	MSGID_GET_FULL_NODE_REV = 20315 //获取全节点

	MSGID_HEIGHTBLOCK      = 20316 //查询邻居节点区块高度
	MSGID_HEIGHTBLOCK_RECV = 20317 //查询邻居节点区块高度_返回

	FUll_NODE_INLINE_MUTIL      = 20318 //全节点上线广播
	FUll_NODE_INLINE_MUTIL_RECV = 20319 //全节点上线广播

	MSGID_GETSTARTBLOCKHEAD      = 20320 //查询邻居节点的起始区块头(针对轻节点的p2p消息)
	MSGID_GETSTARTBLOCKHEAD_RECV = 20321 //查询邻居节点的起始区块头_返回

	MSGID_multicast_swap_transaction = 20322 //接收swap交易广播
)
