// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * rpc请求返回消息
 */
export class PostResult {
    /**
     * Creates a new PostResult instance.
     * @param {Partial<PostResult>} [$$source = {}] - The source object to create the PostResult.
     */
    constructor($$source = {}) {
        if (!("hcode" in $$source)) {
            /**
             * HTTP返回状态码
             * @member
             * @type {number}
             */
            this["hcode"] = 0;
        }
        if (!("code" in $$source)) {
            /**
             * 成功或错误编号
             * @member
             * @type {number}
             */
            this["code"] = 0;
        }
        if (!("msg" in $$source)) {
            /**
             * 错误信息
             * @member
             * @type {string}
             */
            this["msg"] = "";
        }
        if (!("data" in $$source)) {
            /**
             * 返回的数据
             * @member
             * @type {{ [_: string]: any }}
             */
            this["data"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PostResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PostResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField3_0($$parsedSource["data"]);
        }
        return new PostResult(/** @type {Partial<PostResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
