// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: searchnodeinfo.proto

//包名，通过protoc生成时go文件时

package go_protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchNodeInfo struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	SuperId              []byte   `protobuf:"bytes,2,opt,name=SuperId,proto3" json:"SuperId,omitempty"`
	CPuk                 []byte   `protobuf:"bytes,3,opt,name=CPuk,proto3" json:"CPuk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchNodeInfo) Reset()         { *m = SearchNodeInfo{} }
func (m *SearchNodeInfo) String() string { return proto.CompactTextString(m) }
func (*SearchNodeInfo) ProtoMessage()    {}
func (*SearchNodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3c08cb7ad54b44b, []int{0}
}
func (m *SearchNodeInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SearchNodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SearchNodeInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SearchNodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchNodeInfo.Merge(m, src)
}
func (m *SearchNodeInfo) XXX_Size() int {
	return m.Size()
}
func (m *SearchNodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchNodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SearchNodeInfo proto.InternalMessageInfo

func (m *SearchNodeInfo) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *SearchNodeInfo) GetSuperId() []byte {
	if m != nil {
		return m.SuperId
	}
	return nil
}

func (m *SearchNodeInfo) GetCPuk() []byte {
	if m != nil {
		return m.CPuk
	}
	return nil
}

type ShareKey struct {
	Idinfo               *IdInfo  `protobuf:"bytes,1,opt,name=Idinfo,proto3" json:"Idinfo,omitempty"`
	A_DH_PUK             []byte   `protobuf:"bytes,2,opt,name=A_DH_PUK,json=ADHPUK,proto3" json:"A_DH_PUK,omitempty"`
	B_DH_PUK             []byte   `protobuf:"bytes,3,opt,name=B_DH_PUK,json=BDHPUK,proto3" json:"B_DH_PUK,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShareKey) Reset()         { *m = ShareKey{} }
func (m *ShareKey) String() string { return proto.CompactTextString(m) }
func (*ShareKey) ProtoMessage()    {}
func (*ShareKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3c08cb7ad54b44b, []int{1}
}
func (m *ShareKey) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ShareKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ShareKey.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ShareKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareKey.Merge(m, src)
}
func (m *ShareKey) XXX_Size() int {
	return m.Size()
}
func (m *ShareKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareKey.DiscardUnknown(m)
}

var xxx_messageInfo_ShareKey proto.InternalMessageInfo

func (m *ShareKey) GetIdinfo() *IdInfo {
	if m != nil {
		return m.Idinfo
	}
	return nil
}

func (m *ShareKey) GetA_DH_PUK() []byte {
	if m != nil {
		return m.A_DH_PUK
	}
	return nil
}

func (m *ShareKey) GetB_DH_PUK() []byte {
	if m != nil {
		return m.B_DH_PUK
	}
	return nil
}

func init() {
	proto.RegisterType((*SearchNodeInfo)(nil), "protobuf.SearchNodeInfo")
	proto.RegisterType((*ShareKey)(nil), "protobuf.ShareKey")
}

func init() { proto.RegisterFile("searchnodeinfo.proto", fileDescriptor_d3c08cb7ad54b44b) }

var fileDescriptor_d3c08cb7ad54b44b = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x4e, 0x4d, 0x2c,
	0x4a, 0xce, 0xc8, 0xcb, 0x4f, 0x49, 0xcd, 0xcc, 0x4b, 0xcb, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69, 0x52, 0x5c, 0x20, 0x19, 0x88, 0xa8, 0x92, 0x1f, 0x17,
	0x5f, 0x30, 0x58, 0xb5, 0x5f, 0x7e, 0x4a, 0xaa, 0x67, 0x5e, 0x5a, 0xbe, 0x10, 0x1f, 0x17, 0x93,
	0x67, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x4f, 0x10, 0x93, 0x67, 0x8a, 0x90, 0x04, 0x17, 0x7b,
	0x70, 0x69, 0x41, 0x6a, 0x91, 0x67, 0x8a, 0x04, 0x13, 0x58, 0x10, 0xc6, 0x15, 0x12, 0xe2, 0x62,
	0x71, 0x0e, 0x28, 0xcd, 0x96, 0x60, 0x06, 0x0b, 0x83, 0xd9, 0x4a, 0x19, 0x5c, 0x1c, 0xc1, 0x19,
	0x89, 0x45, 0xa9, 0xde, 0xa9, 0x95, 0x42, 0x1a, 0x5c, 0x6c, 0x9e, 0x29, 0x20, 0x17, 0x80, 0x4d,
	0xe3, 0x36, 0x12, 0xd0, 0x83, 0x39, 0x41, 0xcf, 0x33, 0x05, 0x64, 0x57, 0x10, 0x54, 0x5e, 0x48,
	0x82, 0x8b, 0xc3, 0x31, 0xde, 0xc5, 0x23, 0x3e, 0x20, 0xd4, 0x1b, 0x6a, 0x09, 0x9b, 0xa3, 0x8b,
	0x47, 0x40, 0xa8, 0x37, 0x48, 0xc6, 0x09, 0x26, 0x03, 0xb1, 0x87, 0xcd, 0x09, 0x2c, 0xe3, 0x24,
	0x7f, 0xe2, 0x91, 0x1c, 0xe3, 0x85, 0x47, 0x72, 0x8c, 0x0f, 0x1e, 0xc9, 0x31, 0xce, 0x78, 0x2c,
	0xc7, 0x10, 0xc5, 0xab, 0xa7, 0x9f, 0x9e, 0x1f, 0x0f, 0xb3, 0x23, 0x89, 0x0d, 0xcc, 0x32, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x37, 0xd0, 0x23, 0xfe, 0x0f, 0x01, 0x00, 0x00,
}

func (m *SearchNodeInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SearchNodeInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SearchNodeInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.CPuk) > 0 {
		i -= len(m.CPuk)
		copy(dAtA[i:], m.CPuk)
		i = encodeVarintSearchnodeinfo(dAtA, i, uint64(len(m.CPuk)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SuperId) > 0 {
		i -= len(m.SuperId)
		copy(dAtA[i:], m.SuperId)
		i = encodeVarintSearchnodeinfo(dAtA, i, uint64(len(m.SuperId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintSearchnodeinfo(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ShareKey) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ShareKey) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ShareKey) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.B_DH_PUK) > 0 {
		i -= len(m.B_DH_PUK)
		copy(dAtA[i:], m.B_DH_PUK)
		i = encodeVarintSearchnodeinfo(dAtA, i, uint64(len(m.B_DH_PUK)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.A_DH_PUK) > 0 {
		i -= len(m.A_DH_PUK)
		copy(dAtA[i:], m.A_DH_PUK)
		i = encodeVarintSearchnodeinfo(dAtA, i, uint64(len(m.A_DH_PUK)))
		i--
		dAtA[i] = 0x12
	}
	if m.Idinfo != nil {
		{
			size, err := m.Idinfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSearchnodeinfo(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSearchnodeinfo(dAtA []byte, offset int, v uint64) int {
	offset -= sovSearchnodeinfo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SearchNodeInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovSearchnodeinfo(uint64(l))
	}
	l = len(m.SuperId)
	if l > 0 {
		n += 1 + l + sovSearchnodeinfo(uint64(l))
	}
	l = len(m.CPuk)
	if l > 0 {
		n += 1 + l + sovSearchnodeinfo(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ShareKey) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Idinfo != nil {
		l = m.Idinfo.Size()
		n += 1 + l + sovSearchnodeinfo(uint64(l))
	}
	l = len(m.A_DH_PUK)
	if l > 0 {
		n += 1 + l + sovSearchnodeinfo(uint64(l))
	}
	l = len(m.B_DH_PUK)
	if l > 0 {
		n += 1 + l + sovSearchnodeinfo(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovSearchnodeinfo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSearchnodeinfo(x uint64) (n int) {
	return sovSearchnodeinfo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SearchNodeInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSearchnodeinfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SearchNodeInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SearchNodeInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSearchnodeinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSearchnodeinfo
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSearchnodeinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = append(m.Id[:0], dAtA[iNdEx:postIndex]...)
			if m.Id == nil {
				m.Id = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SuperId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSearchnodeinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSearchnodeinfo
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSearchnodeinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SuperId = append(m.SuperId[:0], dAtA[iNdEx:postIndex]...)
			if m.SuperId == nil {
				m.SuperId = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CPuk", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSearchnodeinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSearchnodeinfo
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSearchnodeinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CPuk = append(m.CPuk[:0], dAtA[iNdEx:postIndex]...)
			if m.CPuk == nil {
				m.CPuk = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSearchnodeinfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSearchnodeinfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ShareKey) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSearchnodeinfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ShareKey: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ShareKey: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Idinfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSearchnodeinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSearchnodeinfo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSearchnodeinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Idinfo == nil {
				m.Idinfo = &IdInfo{}
			}
			if err := m.Idinfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field A_DH_PUK", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSearchnodeinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSearchnodeinfo
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSearchnodeinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.A_DH_PUK = append(m.A_DH_PUK[:0], dAtA[iNdEx:postIndex]...)
			if m.A_DH_PUK == nil {
				m.A_DH_PUK = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field B_DH_PUK", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSearchnodeinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSearchnodeinfo
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSearchnodeinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.B_DH_PUK = append(m.B_DH_PUK[:0], dAtA[iNdEx:postIndex]...)
			if m.B_DH_PUK == nil {
				m.B_DH_PUK = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSearchnodeinfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSearchnodeinfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSearchnodeinfo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSearchnodeinfo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSearchnodeinfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSearchnodeinfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSearchnodeinfo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSearchnodeinfo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSearchnodeinfo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSearchnodeinfo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSearchnodeinfo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSearchnodeinfo = fmt.Errorf("proto: unexpected end of group")
)
