// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: searchnodeinfo_v2.proto

//包名，通过protoc生成时go文件时

package go_protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchNodeInfoV2 struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	SuperId              []byte   `protobuf:"bytes,2,opt,name=SuperId,proto3" json:"SuperId,omitempty"`
	CPuk                 []byte   `protobuf:"bytes,3,opt,name=CPuk,proto3" json:"CPuk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchNodeInfoV2) Reset()         { *m = SearchNodeInfoV2{} }
func (m *SearchNodeInfoV2) String() string { return proto.CompactTextString(m) }
func (*SearchNodeInfoV2) ProtoMessage()    {}
func (*SearchNodeInfoV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a5eecffd2b8addf, []int{0}
}
func (m *SearchNodeInfoV2) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SearchNodeInfoV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SearchNodeInfoV2.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SearchNodeInfoV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchNodeInfoV2.Merge(m, src)
}
func (m *SearchNodeInfoV2) XXX_Size() int {
	return m.Size()
}
func (m *SearchNodeInfoV2) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchNodeInfoV2.DiscardUnknown(m)
}

var xxx_messageInfo_SearchNodeInfoV2 proto.InternalMessageInfo

func (m *SearchNodeInfoV2) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *SearchNodeInfoV2) GetSuperId() []byte {
	if m != nil {
		return m.SuperId
	}
	return nil
}

func (m *SearchNodeInfoV2) GetCPuk() []byte {
	if m != nil {
		return m.CPuk
	}
	return nil
}

type ShareKeyV2 struct {
	Idinfo               *IdInfoV2 `protobuf:"bytes,1,opt,name=Idinfo,proto3" json:"Idinfo,omitempty"`
	A_DH_PUK             []byte    `protobuf:"bytes,2,opt,name=A_DH_PUK,json=ADHPUK,proto3" json:"A_DH_PUK,omitempty"`
	B_DH_PUK             []byte    `protobuf:"bytes,3,opt,name=B_DH_PUK,json=BDHPUK,proto3" json:"B_DH_PUK,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ShareKeyV2) Reset()         { *m = ShareKeyV2{} }
func (m *ShareKeyV2) String() string { return proto.CompactTextString(m) }
func (*ShareKeyV2) ProtoMessage()    {}
func (*ShareKeyV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a5eecffd2b8addf, []int{1}
}
func (m *ShareKeyV2) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ShareKeyV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ShareKeyV2.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ShareKeyV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareKeyV2.Merge(m, src)
}
func (m *ShareKeyV2) XXX_Size() int {
	return m.Size()
}
func (m *ShareKeyV2) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareKeyV2.DiscardUnknown(m)
}

var xxx_messageInfo_ShareKeyV2 proto.InternalMessageInfo

func (m *ShareKeyV2) GetIdinfo() *IdInfoV2 {
	if m != nil {
		return m.Idinfo
	}
	return nil
}

func (m *ShareKeyV2) GetA_DH_PUK() []byte {
	if m != nil {
		return m.A_DH_PUK
	}
	return nil
}

func (m *ShareKeyV2) GetB_DH_PUK() []byte {
	if m != nil {
		return m.B_DH_PUK
	}
	return nil
}

func init() {
	proto.RegisterType((*SearchNodeInfoV2)(nil), "protobuf.SearchNodeInfoV2")
	proto.RegisterType((*ShareKeyV2)(nil), "protobuf.ShareKeyV2")
}

func init() { proto.RegisterFile("searchnodeinfo_v2.proto", fileDescriptor_8a5eecffd2b8addf) }

var fileDescriptor_8a5eecffd2b8addf = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x4e, 0x4d, 0x2c,
	0x4a, 0xce, 0xc8, 0xcb, 0x4f, 0x49, 0xcd, 0xcc, 0x4b, 0xcb, 0x8f, 0x2f, 0x33, 0xd2, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69, 0x52, 0xbc, 0x20, 0x49, 0xb8, 0x84,
	0x52, 0x00, 0x97, 0x40, 0x30, 0x58, 0x8f, 0x5f, 0x7e, 0x4a, 0xaa, 0x67, 0x5e, 0x5a, 0x7e, 0x98,
	0x91, 0x10, 0x1f, 0x17, 0x93, 0x67, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x4f, 0x10, 0x93, 0x67,
	0x8a, 0x90, 0x04, 0x17, 0x7b, 0x70, 0x69, 0x41, 0x6a, 0x91, 0x67, 0x8a, 0x04, 0x13, 0x58, 0x10,
	0xc6, 0x15, 0x12, 0xe2, 0x62, 0x71, 0x0e, 0x28, 0xcd, 0x96, 0x60, 0x06, 0x0b, 0x83, 0xd9, 0x4a,
	0x39, 0x5c, 0x5c, 0xc1, 0x19, 0x89, 0x45, 0xa9, 0xde, 0xa9, 0x95, 0x61, 0x46, 0x42, 0x5a, 0x5c,
	0x6c, 0x9e, 0x29, 0x20, 0xb7, 0x80, 0xcd, 0xe3, 0x36, 0x12, 0xd2, 0x83, 0xb9, 0x44, 0xcf, 0x33,
	0x05, 0x62, 0x5f, 0x10, 0x54, 0x85, 0x90, 0x04, 0x17, 0x87, 0x63, 0xbc, 0x8b, 0x47, 0x7c, 0x40,
	0xa8, 0x37, 0xd4, 0x22, 0x36, 0x47, 0x17, 0x8f, 0x80, 0x50, 0x6f, 0x90, 0x8c, 0x13, 0x4c, 0x06,
	0x62, 0x17, 0x9b, 0x13, 0x58, 0xc6, 0x49, 0xfe, 0xc4, 0x23, 0x39, 0xc6, 0x0b, 0x8f, 0xe4, 0x18,
	0x1f, 0x3c, 0x92, 0x63, 0x9c, 0xf1, 0x58, 0x8e, 0x21, 0x8a, 0x57, 0x4f, 0x3f, 0x3d, 0x3f, 0x1e,
	0x66, 0x4b, 0x12, 0x1b, 0x98, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xf1, 0xd3, 0xf7, 0x33,
	0x1b, 0x01, 0x00, 0x00,
}

func (m *SearchNodeInfoV2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SearchNodeInfoV2) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SearchNodeInfoV2) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.CPuk) > 0 {
		i -= len(m.CPuk)
		copy(dAtA[i:], m.CPuk)
		i = encodeVarintSearchnodeinfoV2(dAtA, i, uint64(len(m.CPuk)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SuperId) > 0 {
		i -= len(m.SuperId)
		copy(dAtA[i:], m.SuperId)
		i = encodeVarintSearchnodeinfoV2(dAtA, i, uint64(len(m.SuperId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintSearchnodeinfoV2(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ShareKeyV2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ShareKeyV2) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ShareKeyV2) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.B_DH_PUK) > 0 {
		i -= len(m.B_DH_PUK)
		copy(dAtA[i:], m.B_DH_PUK)
		i = encodeVarintSearchnodeinfoV2(dAtA, i, uint64(len(m.B_DH_PUK)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.A_DH_PUK) > 0 {
		i -= len(m.A_DH_PUK)
		copy(dAtA[i:], m.A_DH_PUK)
		i = encodeVarintSearchnodeinfoV2(dAtA, i, uint64(len(m.A_DH_PUK)))
		i--
		dAtA[i] = 0x12
	}
	if m.Idinfo != nil {
		{
			size, err := m.Idinfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSearchnodeinfoV2(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSearchnodeinfoV2(dAtA []byte, offset int, v uint64) int {
	offset -= sovSearchnodeinfoV2(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SearchNodeInfoV2) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovSearchnodeinfoV2(uint64(l))
	}
	l = len(m.SuperId)
	if l > 0 {
		n += 1 + l + sovSearchnodeinfoV2(uint64(l))
	}
	l = len(m.CPuk)
	if l > 0 {
		n += 1 + l + sovSearchnodeinfoV2(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ShareKeyV2) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Idinfo != nil {
		l = m.Idinfo.Size()
		n += 1 + l + sovSearchnodeinfoV2(uint64(l))
	}
	l = len(m.A_DH_PUK)
	if l > 0 {
		n += 1 + l + sovSearchnodeinfoV2(uint64(l))
	}
	l = len(m.B_DH_PUK)
	if l > 0 {
		n += 1 + l + sovSearchnodeinfoV2(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovSearchnodeinfoV2(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSearchnodeinfoV2(x uint64) (n int) {
	return sovSearchnodeinfoV2(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SearchNodeInfoV2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSearchnodeinfoV2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SearchNodeInfoV2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SearchNodeInfoV2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSearchnodeinfoV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSearchnodeinfoV2
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSearchnodeinfoV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = append(m.Id[:0], dAtA[iNdEx:postIndex]...)
			if m.Id == nil {
				m.Id = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SuperId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSearchnodeinfoV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSearchnodeinfoV2
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSearchnodeinfoV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SuperId = append(m.SuperId[:0], dAtA[iNdEx:postIndex]...)
			if m.SuperId == nil {
				m.SuperId = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CPuk", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSearchnodeinfoV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSearchnodeinfoV2
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSearchnodeinfoV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CPuk = append(m.CPuk[:0], dAtA[iNdEx:postIndex]...)
			if m.CPuk == nil {
				m.CPuk = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSearchnodeinfoV2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSearchnodeinfoV2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ShareKeyV2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSearchnodeinfoV2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ShareKeyV2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ShareKeyV2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Idinfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSearchnodeinfoV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSearchnodeinfoV2
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSearchnodeinfoV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Idinfo == nil {
				m.Idinfo = &IdInfoV2{}
			}
			if err := m.Idinfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field A_DH_PUK", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSearchnodeinfoV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSearchnodeinfoV2
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSearchnodeinfoV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.A_DH_PUK = append(m.A_DH_PUK[:0], dAtA[iNdEx:postIndex]...)
			if m.A_DH_PUK == nil {
				m.A_DH_PUK = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field B_DH_PUK", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSearchnodeinfoV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSearchnodeinfoV2
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSearchnodeinfoV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.B_DH_PUK = append(m.B_DH_PUK[:0], dAtA[iNdEx:postIndex]...)
			if m.B_DH_PUK == nil {
				m.B_DH_PUK = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSearchnodeinfoV2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSearchnodeinfoV2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSearchnodeinfoV2(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSearchnodeinfoV2
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSearchnodeinfoV2
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSearchnodeinfoV2
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSearchnodeinfoV2
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSearchnodeinfoV2
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSearchnodeinfoV2
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSearchnodeinfoV2        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSearchnodeinfoV2          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSearchnodeinfoV2 = fmt.Errorf("proto: unexpected end of group")
)
